export const actionType={
    ADD_CATEGORY:"ADD_CATEGORY",
    UPDATE_CATEGORY:"UPDATE_CATEGORY",
    REMOVE_CATEGORY:"REMOVE_CATEGORY",
    FETCH_CATEGORY:"FETCH_CATEGORY",

    LOGIN_USER:"LOGIN_USER",
    LOGIN_USER_SUCCESS:"LOGIN_USER_SUCCESS",
    CREATE_USER:"CREATE_USER",
    CREATE_USER_SUCCESS:"CREATE_USER_SUCCESS",
    FETCH_USER:"FETCH_USER",
    FETCH_USER_SUCCESS:"FETCH_USER_SUCCESS",


    ERROR:"ERROR",
    HIDE_LOADING:"HIDE_LOADING",
    SHOW_LOADING:"SHOW_LOADING"
}